/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginInGUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import UserGUI.UserList;
import UserGUI.UserListService;
import UserGUI.UserListTableModel;

/**
 *
 * @author lenovo
 */
public class LoginIFrame extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	public LoginIFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		btn_login = new javax.swing.JButton();
		btn_reset = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		username = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		password = new javax.swing.JPasswordField();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(
				new javax.swing.OverlayLayout(getContentPane()));

		jPanel2.setBackground(new java.awt.Color(246, 172, 45));
		jPanel2.setPreferredSize(new java.awt.Dimension(0, 60));

		btn_login.setBackground(new java.awt.Color(82, 185, 141));
		btn_login.setText("Log in");
		btn_login.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_loginActionPerformed(evt);
			}
		});

		btn_reset.setBackground(new java.awt.Color(153, 153, 153));
		btn_reset.setText("Reset");
		btn_reset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_resetActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout
						.createSequentialGroup()
						.addGap(108, 108, 108)
						.addComponent(btn_reset)
						.addGap(27, 27, 27)
						.addComponent(btn_login)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(btn_login)
														.addComponent(btn_reset))
										.addContainerGap(27, Short.MAX_VALUE)));

		jPanel3.setBackground(new java.awt.Color(255, 247, 152));
		jPanel3.setPreferredSize(new java.awt.Dimension(400, 200));

		username.setText("800001");
		username.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				usernameActionPerformed(evt);
			}
		});

		jLabel1.setText("User Name：");

		jLabel3.setText("Password：");

		password.setText("111");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(37, 37, 37)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1)
														.addComponent(jLabel3))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(password)
														.addComponent(
																username,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																186,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(93, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(60, 60, 60)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																username,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel1))
										.addGap(37, 37, 37)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																password,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(61, Short.MAX_VALUE)));

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/login.jpg"))); // NOI18N
		jLabel2.setPreferredSize(new java.awt.Dimension(0, 40));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
						400, Short.MAX_VALUE)
				.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												100,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		getContentPane().add(jPanel1);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_loginActionPerformed
		// TODO add your handling code here:
		String user_name = username.getText().trim();
		String pass_word = new String(password.getPassword());

		if (user_name.length() == 0) {
			JOptionPane.showMessageDialog(null, "user name cannot be empty!");
			return;
		} else if (pass_word.length() == 0) {
			JOptionPane.showMessageDialog(null, "password cannot be empty!");
			return;
		} else {
			UserListTableModel newModel = new UserListTableModel();
			UserListService userListService = new UserListService(
					newModel.getEntityManager());
			if (userListService.readUser(Integer.parseInt(username.getText())) == null) {
				JOptionPane.showMessageDialog(null, "User doesn't exist!!!");
			} else if (userListService
					.readUser(Integer.parseInt(username.getText()))
					.getPassword().equals(pass_word) == true) {
				if (userListService
						.readUser(Integer.parseInt(username.getText()))
						.getUser_type().equals("Administrator") == true) {

					System.out.println(Integer.parseInt(username.getText()));
					new WelcomeFrame(userListService.readUser(Integer
							.parseInt(username.getText())))
							.runWelcomeFrame(userListService.readUser(Integer
									.parseInt(username.getText())));
				} else if (userListService
						.readUser(Integer.parseInt(username.getText()))
						.getUser_type().equals("Student") == true) {
					new UserWelcomeFrame(userListService.readUser(Integer
							.parseInt(username.getText())))
							.runUserWelcome(userListService.readUser(Integer
									.parseInt(username.getText())));
				} else if (userListService
						.readUser(Integer.parseInt(username.getText()))
						.getUser_type().equals("Partner") == true) {
					new UserWelcomeFrame(userListService.readUser(Integer
							.parseInt(username.getText())))
							.runUserWelcome(userListService.readUser(Integer
									.parseInt(username.getText())));

				} else if (userListService
						.readUser(Integer.parseInt(username.getText()))
						.getUser_type().equals("Faculty Advisor") == true) {
					new UserWelcomeFrame(userListService.readUser(Integer
							.parseInt(username.getText())))
							.runUserWelcome(userListService.readUser(Integer
									.parseInt(username.getText())));

				}
				this.dispose();
			} else {
				JOptionPane.showMessageDialog(null, "Wrong password!");
				return;
			}
		}
	}// GEN-LAST:event_btn_loginActionPerformed

	private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_resetActionPerformed
		// TODO add your handling code here:
		username.setText("");
		password.setText("");
	}// GEN-LAST:event_btn_resetActionPerformed

	private void usernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_usernameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_usernameActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public void runLoginFrame() {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginIFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginIFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginIFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginIFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginIFrame().setVisible(true);
			}
		});
	}

	public static void main(String args[]) {
		new LoginIFrame().runLoginFrame();
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btn_login;
	private javax.swing.JButton btn_reset;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPasswordField password;
	private javax.swing.JTextField username;
	// End of variables declaration//GEN-END:variables
}
