/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LoginInGUI;

import BudgetGUI.BudgetEdtFrame;
import ProjectGUI.ProjectEdtFrame;
import RecordGUI.RecordEdtFrame;
import TeamGUI.TeamEdtFrame;
import TimeLineGUI.TimelineEdtFrame;
import UserGUI.UserList;
import UserGUI.UserListGUI;


/**
 *
 * @author lenovo
 */
public class WelcomeFrame extends javax.swing.JFrame {
	public UserList currentUser;

	/**
	 * Creates new form MainFrame
	 */
	public WelcomeFrame(UserList cc) {
		initComponents(cc);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents(UserList bb) {

		jMenu5 = new javax.swing.JMenu();
		jMenu6 = new javax.swing.JMenu();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		userManagementButton = new javax.swing.JButton();
		buttonManagementButton = new javax.swing.JButton();
		teamManagementButton = new javax.swing.JButton();
		timelineManagementButton = new javax.swing.JButton();
		recordButton = new javax.swing.JButton();
		budgetManagementButton = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jLabel10 = new javax.swing.JLabel();
		backButton = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		InfoTextArea = new javax.swing.JTextArea();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu5.setText("jMenu5");
		jMenu6.setText("jMenu6");
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(0, 0, 0));
		jPanel1.setPreferredSize(new java.awt.Dimension(615, 120));
		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/mainlogo.jpg"))); // NOI18N
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabel2));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		jPanel2.setBackground(new java.awt.Color(246, 172, 45));

		userManagementButton.setBackground(new java.awt.Color(251, 197, 97));
		userManagementButton.setText("User Management");
		userManagementButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						userManagementButtonActionPerformed(evt);
					}
				});

		buttonManagementButton.setBackground(new java.awt.Color(251, 197, 97));
		buttonManagementButton.setText("Project Management");
		buttonManagementButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						buttonManagementButtonActionPerformed(evt);
					}
				});

		teamManagementButton.setBackground(new java.awt.Color(251, 197, 97));
		teamManagementButton.setText("Team Management");
		teamManagementButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						teamManagementButtonActionPerformed(evt);
					}
				});

		timelineManagementButton
				.setBackground(new java.awt.Color(251, 197, 97));
		timelineManagementButton.setText("TimeLine Management");
		timelineManagementButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						timelineManagementButtonActionPerformed(evt);
					}
				});

		recordButton.setBackground(new java.awt.Color(251, 197, 97));
		recordButton.setText("Record");
		recordButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				recordButtonActionPerformed(evt);
			}
		});

		budgetManagementButton.setBackground(new java.awt.Color(251, 197, 97));
		budgetManagementButton.setText("Budget Management");
		budgetManagementButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						budgetManagementButtonActionPerformed(evt);
					}
				});

		jLabel10.setBackground(new java.awt.Color(246, 172, 145));
		jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/scu.png"))); // NOI18N

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel5Layout.createSequentialGroup().addComponent(jLabel10)
						.addGap(0, 0, Short.MAX_VALUE)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 174,
				Short.MAX_VALUE));

		backButton.setBackground(new java.awt.Color(251, 197, 97));
		backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/back.png"))); // NOI18N
		backButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel5,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																userManagementButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																buttonManagementButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																teamManagementButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																recordButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																budgetManagementButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																timelineManagementButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																backButton,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(114, 114, 114)
										.addComponent(
												userManagementButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												buttonManagementButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												teamManagementButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												timelineManagementButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												budgetManagementButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												recordButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												40,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												jPanel5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(462, 462, 462)
										.addComponent(
												backButton,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												41,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(229, 229, 229)));

		jPanel4.setBackground(new java.awt.Color(255, 247, 152));

		jLabel5.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
		jLabel5.setForeground(new java.awt.Color(255, 0, 51));
		jLabel5.setText("Welcome!");

		jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img/foot.jpg"))); // NOI18N

		InfoTextArea.setBackground(new java.awt.Color(255, 247, 152));
		InfoTextArea.setColumns(20);
		InfoTextArea.setRows(5);
		InfoTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(
				null, "Your Information",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION,
				new java.awt.Font("Bookman Old Style", 0, 12),
				new java.awt.Color(255, 0, 153))); // NOI18N
		InfoTextArea.append("User Name: " + bb.getUser_name());
		InfoTextArea.append("\n\n");
		InfoTextArea.append("User Type: " + bb.getUser_type());
		InfoTextArea.append("\n\n");
		InfoTextArea.append("User Address: " + bb.getAddress());
		InfoTextArea.append("\n\n");
		InfoTextArea.append("User Email: " + bb.getEmail());
		InfoTextArea.append("\n\n");
		InfoTextArea.append("User Phone Number: " + bb.getPhone());
		jScrollPane2.setViewportView(InfoTextArea);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel12,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																997,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(25,
																				25,
																				25)
																		.addComponent(
																				jLabel5))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(101,
																				101,
																				101)
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				402,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(23, 23, 23)
										.addComponent(jLabel5)
										.addGap(18, 18, 18)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												340,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												jLabel12,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														600, Short.MAX_VALUE)
												.addComponent(
														jPanel4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														600, Short.MAX_VALUE))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel4,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void buttonManagementButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonManagementButtonActionPerformed
		// TODO add your handling code here:
		new ProjectEdtFrame().runProject();
		this.dispose();
	}// GEN-LAST:event_buttonManagementButtonActionPerformed

	private void userManagementButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userManagementButtonActionPerformed
		// TODO add your handling code here:
		new UserListGUI().runUser();
		this.dispose();
	}// GEN-LAST:event_userManagementButtonActionPerformed

	private void teamManagementButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userManagementButtonActionPerformed
		// TODO add your handling code here:
		new TeamEdtFrame().runTeam();
		this.dispose();
	}

	private void timelineManagementButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userManagementButtonActionPerformed
		// TODO add your handling code here:
		new TimelineEdtFrame().runTimeline();
		this.dispose();
	}

	private void recordButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_recordButtonActionPerformed
		// TODO add your handling code here:
		new RecordEdtFrame().runRecord();
		this.dispose();
	}// GEN-LAST:event_recordButtonActionPerformed

	private void budgetManagementButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_budgetManagementButtonActionPerformed
		// TODO add your handling code here:
		new BudgetEdtFrame().runBudget();
		this.dispose();
	}// GEN-LAST:event_budgetManagementButtonActionPerformed

	private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backButtonActionPerformed
		// TODO add your handling code here:
		new LoginIFrame().runLoginFrame();
		this.dispose();
	}// GEN-LAST:event_backButtonActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public void runWelcomeFrame(UserList a) {
		//System.out.println(a.getUser_name());
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(WelcomeFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(WelcomeFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(WelcomeFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(WelcomeFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new WelcomeFrame(a).setVisible(true);
			}
		});
	}

//	public static void main(String args[]) {
//		new WelcomeFrame().runWelcomeFrame(null);
//	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextArea InfoTextArea;
	private javax.swing.JButton backButton;
	private javax.swing.JButton budgetManagementButton;
	private javax.swing.JButton buttonManagementButton;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenu jMenu6;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JButton recordButton;
	private javax.swing.JButton teamManagementButton;
	private javax.swing.JButton timelineManagementButton;
	private javax.swing.JButton userManagementButton;
	// End of variables declaration//GEN-END:variables
}
